/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Messages */
        get: operations["session_messages_api_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /** Turn Id */
            turn_id: string | null;
            /** Created At */
            created_at: string;
            stats: components["schemas"]["TurnStats"] | null;
            /** Tools */
            tools: components["schemas"]["ToolCallOut"][];
        };
        /**
         * RetrievalHit
         * @description One passage the UI can link to, built by the knowledge renderer.
         *
         *     `citation` is the `path:line` form the system prompt tells the model to
         *     cite, so the UI and the answer text agree on how a source is named.
         */
        RetrievalHit: {
            /** Path */
            path: string;
            /** Citation */
            citation: string;
            /** Start Line */
            start_line: number;
            /** Source Type */
            source_type: string;
        };
        /** ServerStatus */
        ServerStatus: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Available */
            available: boolean;
            /** Tool Count */
            tool_count: number;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Turn Count */
            turn_count: number;
        };
        /** Snapshot */
        Snapshot: {
            /** Repo */
            repo: string;
            /** Commit */
            commit: string;
        };
        /** Status */
        Status: {
            /** Model */
            model: string;
            /** Corpus Repos */
            corpus_repos: string[];
            /** Snapshots */
            snapshots: components["schemas"]["Snapshot"][];
            /** Servers */
            servers: components["schemas"]["ServerStatus"][];
            /** Tools */
            tools: string[];
        };
        /**
         * ToolCallOut
         * @description One persisted tool call, shaped for the card that renders it.
         *
         *     `RetrievalHit` is the model the `retrieval.hits` frame carries, so a
         *     replayed card and a live one are fed identical source links.
         */
        ToolCallOut: {
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Preview */
            preview: string | null;
            /** Hits */
            hits: components["schemas"]["RetrievalHit"][];
            /** Duration Ms */
            duration_ms: number | null;
        };
        /**
         * TurnStats
         * @description What one turn cost and how long it took.
         *
         *     `ttft_ms` runs to the first `TextDelta`, so a turn that searched for eight
         *     seconds before writing a word reports eight seconds -- what the user waits
         *     on, not the model's prefill latency. `cost_usd` is None when the model is
         *     not priced; see `core.pricing`.
         */
        TurnStats: {
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
            /** Ttft Ms */
            ttft_ms: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Steps */
            steps: number;
            /** Tool Calls */
            tool_calls: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Client-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_messages_api_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
